apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: unforgettable-docs
    docker:
      buildArgs:
        BASE_URL: "{{.BASE_URL}}"
        URL: "{{.URL}}"
        STAGING: "{{.STAGING}}"